# Generated by Django 3.2.9 on 2021-11-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resumedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=800)),
                ('dob', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('hobbies', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('martial_status', models.CharField(max_length=100)),
                ('social_media', models.URLField(max_length=800)),
                ('instagram_url', models.URLField(max_length=800)),
                ('linkedIn_url', models.URLField(max_length=800)),
                ('degree', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=200)),
                ('skills1', models.CharField(max_length=200)),
                ('skills2', models.CharField(max_length=200)),
                ('skills3', models.CharField(max_length=200)),
                ('skills4', models.CharField(max_length=200)),
                ('achievements', models.CharField(max_length=400)),
                ('languages', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimages')),
            ],
        ),
    ]
