# Generated by Django 3.2.9 on 2021-12-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_auto_20211204_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='fname',
            field=models.CharField(blank=True, default='name', max_length=100),
        ),
    ]
