# Generated by Django 3.2.9 on 2021-12-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_alter_resumedata_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='address',
            field=models.CharField(blank=True, default='Proper address', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='b_year',
            field=models.CharField(blank=True, default='bachelors degree year', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='bd',
            field=models.CharField(blank=True, default='bachelors degree degree', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='binst',
            field=models.CharField(blank=True, default='bachelors degree institute', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='bt',
            field=models.CharField(blank=True, default='bachelors degree town', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='city',
            field=models.CharField(blank=True, default='city', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='company_name',
            field=models.CharField(blank=True, default='company Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='company_name1',
            field=models.CharField(blank=True, default='company Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='company_name2',
            field=models.CharField(blank=True, default='company Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='email',
            field=models.EmailField(blank=True, default='abc@gmail.com', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='end_date',
            field=models.CharField(blank=True, default='end Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='end_date1',
            field=models.CharField(blank=True, default='end Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='end_date2',
            field=models.CharField(blank=True, default='end Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='hobbies',
            field=models.CharField(blank=True, default='hobbies', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='job_town',
            field=models.CharField(blank=True, default='job Town', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='job_town1',
            field=models.CharField(blank=True, default='job Town', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='job_town2',
            field=models.CharField(blank=True, default='job Town', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='jobdes',
            field=models.CharField(blank=True, default='job Designation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='jobdes1',
            field=models.CharField(blank=True, default='job Designation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='jobdes2',
            field=models.CharField(blank=True, default='job Designation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='jobdescription',
            field=models.CharField(blank=True, default='Job Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='jobdescription1',
            field=models.CharField(blank=True, default='Job Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='jobdescription2',
            field=models.CharField(blank=True, default='Job Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='linkedIn_url',
            field=models.URLField(blank=True, default='linkedin.com', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='lname',
            field=models.CharField(blank=True, default='lname', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='nationality',
            field=models.CharField(blank=True, default='nationality', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='p_year',
            field=models.CharField(blank=True, default='post degreeyear', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='pd',
            field=models.CharField(blank=True, default='post graduation degree', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='phone',
            field=models.CharField(blank=True, default='123456789', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='pinst',
            field=models.CharField(blank=True, default='post degree institute', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='place_of_birth',
            field=models.CharField(blank=True, default='place_of_birth', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='pt',
            field=models.CharField(blank=True, default='post degree town', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='ref_company',
            field=models.CharField(blank=True, default='reference_company', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='ref_des',
            field=models.CharField(blank=True, default='reference_des', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='ref_email',
            field=models.CharField(blank=True, default='reference_email', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='ref_name',
            field=models.CharField(blank=True, default='reference_name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='ref_phone',
            field=models.CharField(blank=True, default='reference_phone', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='resumeobj',
            field=models.CharField(blank=True, default='resumeobj', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='skills',
            field=models.CharField(blank=True, default='skills1', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='start_date',
            field=models.CharField(blank=True, default='start Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='start_date1',
            field=models.CharField(blank=True, default='start Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='start_date2',
            field=models.CharField(blank=True, default='start Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='website',
            field=models.URLField(blank=True, default='websiteaddress.com', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='zipcode',
            field=models.CharField(blank=True, default='400607', max_length=10, null=True),
        ),
    ]
